dashboard/forms.py
from flask_wtf import FlaskForm
from wtforms import PasswordField, StringField, SubmitField, ValidationError, SelectField, IntegerField
from wtforms.validators import DataRequired, Length, NumberRange
from ..models import BankAccount, Bank
# from .utils import get_bank_list

class PaymentForm(FlaskForm):
	pass

class BankForm(FlaskForm):

	bank = SelectField('Bank Name',
	coerce=int,
	 validators=[DataRequired()])
	account_name = StringField('Account Name', validators=[DataRequired()])
	account_number = StringField('Account Number', validators=[DataRequired(), Length(min=10)])

	def __init__(self, *args, **kwargs):
		super(BankForm, self).__init__(*args, **kwargs)
		self.bank.choices = Bank.get_banklist()

	def validate_account_number(self, field):
		# if BankAccount.query.filter_by(account_number = field.data).first():
		# 	raise ValidationError('Bank Account already exists')
		if type(int(field.data)) is not int:
			raise ValidationError('Please provide a valid account number')

dashboard/__init__.py
from flask import Blueprint

dashboard = Blueprint('dashboard', __name__)
from . import views

dashboard/views.py
import sys
import json
import logging
from flask import render_template, abort, request, Response, redirect, flash, url_for, g, Markup
from flask_login import login_required, current_user
import miniwalletapp as app
from miniwalletapp.config import PAYSTACK_SECRET_KEY as srk
from miniwalletapp.models import User, TransactionLog, BankAccount, WithdrawalRequest

from .utils import init_transaction, verify_hook, resend_otp, finalize_withdrawal
from .forms import BankForm
from . import dashboard as dbp
from ..models import BankAccount, Bank, OTPLog

login_manager = app.login_manager
data = None

@login_manager.user_loader
def load_user(user_id):
	try: 
		user = User.query.filter(User.id == int(user_id)).first()
		return user
	except:
		return None


@dbp.route('/dashboard', methods=['GET'])
@login_required
def dashboard(*args, **kwargs):

	trlogs = TransactionLog.query.filter_by(marked=True).order_by(TransactionLog.timestamp.desc()).paginate(1,10,error_out=False)
	
	return render_template('dashboard.html', title="Dashboard", trlogs = trlogs)



@dbp.route('/withdraw', methods=['GET', 'POST'])
@login_required
def withdrawal():
	if current_user.validate_bank_account():
		if request.method == 'POST':
			amount = int(request.form['amount'])
			if amount is not None and amount > 100:
				if current_user.balance >  amount:
					withdrawal = current_user.withdraw(amount)
					if withdrawal['status']:
						flash('Your withdrawal was successful, Your acccount will be credited shortly')
					else:
						flash(withdrawal['message'])
					return redirect(url_for('dashboard.dashboard'))
	else:
		message = Markup('<a href="' + url_for('dashboard.bank_settings') + '">Please, provide bank account details before continuing to withdrawals</a>')
		flash(message)



	return render_template('withdrawal.html', title="withdraw")


@dbp.route('/deposit', methods=['GET', 'POST'])
@login_required
def deposit():
	data = {}
	if request.method == 'GET':
		logging.error('deposit get request')
		refcode = request.args.get('ref', None)
		if refcode:
			trlog = TransactionLog.query.filter_by(code=refcode).first()
			logging.error('trlog is', trlog)
			logging.error('type trlog is', type(trlog))
			logging.error('trlog marked is', trlog.marked)
			if trlog:
				if not trlog.marked:
					trlog = trlog.remit_pay()
				if trlog.marked:
					flash("You deposit has been completed successfully")
					data['url'] = url_for('dashboard.dashboard')
					do_json = request.args.get('json', False)
					if do_json:return Response(json.dumps(data), mimetype='application/json', status=201)
			else:
				flash("Opps! something went wrong with your transaction reference")
	elif (request.method == 'POST'):

		form = request.get_json(force=True) 
		if form:
			amount = int(form['amount'])
			if amount >= 100:
				ref = init_transaction((amount * 100), current_user.email)
				
				
				data['reference'] = ref
				data['amount'] = amount * 100
				data['email'] = current_user.email 
				return Response(json.dumps(data), mimetype='application/json', status=201)
		else:
			return Response(json.dumps(data), mimetype='application/json', status=406)



	# if request.method== 'POST':
	# 	if amount_form.validate():



	return render_template("deposit.html", title="deposit", data=data)



@dbp.route('/settings')
@login_required
def account_settings():
			

	return render_template("settings.html", title="Settings", data=data)



@dbp.route('/settings/bank_account', methods=['GET', 'POST'])
@login_required
def bank_settings():
	bnk_acc = current_user.get_bank_account()
	form = BankForm(request.form)	
	if request.method == 'GET' and bnk_acc:
	
		form = BankForm(bank = bnk_acc.bank_id,
			account_name = bnk_acc.account_name,
			account_number = bnk_acc.account_number)
		form.bank.data = bnk_acc.bank_id
	
	if request.method == 'POST':
		if form.validate_on_submit():
			bank = Bank.query.filter_by(id=form.bank.data).first()
			uid = current_user.get_id()
			if bnk_acc is not None:
				bnk_acc.bank_id = form.bank.data
				bnk_acc.account_name = form.account_name.data
				bnk_acc.account_number = (form.account_number.data).strip()
				flash("Your bank account details have been updated successfully")
			else:
				bnk_acc = BankAccount(bank_id = form.bank.data,
					account_name = form.account_name.data,
					account_number = form.account_number.data,
					user_id = uid )
				app.db.session.add(bnk_acc)
				flash("Your bank account details have been save successfully")
			app.db.session.commit()
	return render_template("bank_settings.html", title="Bank Accounts", data=data, form=form)



@dbp.route('/webhook/' + srk, methods=['POST'])
def webhook():
	if verify_hook(request):
		logging.error('passed hooktest')
		data = request.json
		resp_data = data['data']
		logging.error('data is', data)
		if data['event'] == 'transfer.success':
			logging.error('passed transfer success')
			trlog = TransactionLog.query.filter_by(code=resp_data['transfer_code']).first()
			if trlog is not None:
				trlog = trlog.remit_pay()
			return Response({}, status=200)
		elif data['event'] == 'transfer.failed':
			trlog = TransactionLog.query.filter_by(code=resp_data['transfer_code']).first()
			if trlog is not None:
				trlog = trlog.reverse_pay()
			return Response({}, status=200)

		elif data['event'] == 'charge.success':
			trlog = TransactionLog.query.filter_by(code=resp_data['reference']).first()
			if trlog is not None:
				trlog.amount = data['data']['amount']
				trlog = trlog.remit_pay()

			return Response({}, status=200)
		# return Response({}, status=200)
	return Response({}, status=400) #non 200


@dbp.route('/otp_setting/', methods=['GET', 'POST'])
def otp_setting():
	otplogs = OTPLog.query.order_by(OTPLog.timestamp.desc()).paginate(1,10,error_out=False)
	mode = OTPLog.get_mode()
	if request.method == 'POST':
		logging.error('submit_button is', request.form['submit_button'])
		if request.form['submit_button'] == 'disable-otp':
			message = OTPLog.disable_otp()
			flash(message)

		elif request.form['submit_button'] == 'enable-otp':
			message = OTPLog.enable_otp()
			flash(message)
			mode = OTPLog.get_mode()

		elif request.form['submit_button'] == 'submit-otp':
			if int(request.form['otp-code']):
				message = OTPLog.disable_otp(code = int(request.form['otp-code']))
				flash(message)
				mode = OTPLog.get_mode()
	return render_template("otp_setting.html", otpstatus = mode, title="OTP Settings", otplogs = otplogs)


@dbp.route('/withdrawal_setting/', methods=['GET', 'POST'])
def confirm_withdrawals():
	data = {}
	otp_mode = True #OTPLog.get_mode()
	submit_button = None
	trlog = None
	if request.method == 'POST':
		# withdrawals = request.form.getlist('withdrawals', None)
		# print('Request.forms is', request.form, file=sys.stderr)
		trlog = request.form.get('trlog', None)
		submit_button = request.form.get('submit_button', None)
		# if submit_button == 'resend-otp':
		# 	if trlog:
		# 		response = resend_otp(trlog)
		# 		print('response is', response, file=sys.stderr)
		# 		submit_button =  'resent-otp'
		# 		flash(response['message'])
		# 	else:
		# 		flash("Oops! something went wrong, pleae select a valid withdrawal")
		if trlog:
			wreq = WithdrawalRequest.query.filter_by(id=trlog).first()

			if  submit_button == 'confim-withdrawal':
				response = wreq.accept()
				flash(response['message'])
			elif  submit_button == 'deny-withdrawal':
				print('wreq is ', wreq, file=sys.stderr)
				if wreq.deny():
					flash("The withdrawal has been denied and the funds credited back to user's balance")
				else:
					flash('Oops! an error occured')
		return redirect(url_for('dashboard.confirm_withdrawals'))
		# elif  submit_button == 'submit-otp':
		# 	otp_code = request.form.get('otp_code', None)

		# 	if otp_code:
		# 		# trlog_item = trlog.query.filter_by(code=trlog)
		# 		# response = trlog_item.confirm_withdrawal(otp_code)
		# 		response = finalize_withdrawal(trlog, int(otp_code))
		# 		if response:
		# 			flash(response['message'])
		# 		else:
		# 			flash('an error occured!')
		# 	submit_button = None

	# otplogs = OTPLog.query.order_by(OTPLog.timestamp.desc()).paginate(1,10,error_out=False)
	# mode = OTPLog.get_mode()
	# if request.method == 'POST':
	# 	logging.error('submit_button is', request.form['submit_button'])
	# 	if request.form['submit_button'] == 'disable-otp':
	# 		message = OTPLog.disable_otp()
	# 		flash(message)

	# 	elif request.form['submit_button'] == 'enable-otp':
	# 		message = OTPLog.enable_otp()
	# 		flash(message)
	# 		mode = OTPLog.get_mode()

	# 	elif request.form['submit_button'] == 'submit-otp':
	# 		if int(request.form['otp-code']):
	# 			message = OTPLog.disable_otp(code = int(request.form['otp-code']))
	# 			flash(message)
	# 			mode = OTPLog.get_mode()
	trlogs = WithdrawalRequest.query.all()
	print('Withdrawal requests is', trlogs, file=sys.stderr)

	return render_template("confirm_withdrawal.html",
		title="Withdrawal Settings",
		trlogs = trlogs, 
		otp_mode = otp_mode,
		trlog = trlog,
		submit_button=submit_button)

templates/bank_settings.html
{% extends "dashboard.html" %}


	{% block dashbody %}
		<div class="col-md-4">	
				<div class="container">
					<div class="row">
					<form action="{{url_for('dashboard.bank_settings')}}" method="post" style="width:98%;">

						<div class="row">

							<label for="banks">
							{% for error in form.bank.errors %}
							    {{ error }}  
							    <br>
							{% endfor %}
							{{ form.bank(class_="form-control")}}

							</label>
						</div>
						<div class="row" style="margin-top:5%;">

							<label for="account_name">Account Name</label>
						{% for error in form.account_name.errors %}
							    {{ error }} 
							    <br> 
							{% endfor %}
							<input type="text" class="form-control" name="account_name" id="account_name" value="{{ form.account_name.data }}">
						</div>
						<div class="row" style="margin-top:5%;">

							<label for="account_number">
								Account Number
							</label>
							{% for error in form.account_number.errors %}
							    {{ error }}  
							    <br>
							{% endfor %}
							<input type="text" class="form-control" id="account_number" name="account_number" value="{{ form.account_number.data }}">
						</div>
						
						{{ form.csrf_token }}

						<div class="form-row"  style="margin-top:5%;">
							<button class="btn btn-primary col-md-6 ml-auto">Add Account Details</button>
						</div>

					</form>

				</div>



				</div>
		</div>

			<div class="col-md-5">
				<ul class="list-group">

  <li class="list-group-item">Cras justo odio</li>
  <li class="list-group-item">Dapibus ac facilisis in</li>
  <li class="list-group-item">Morbi leo risus</li>
  <li class="list-group-item">Porta ac consectetur ac</li>
  <li class="list-group-item">Vestibulum at eros</li>
</ul>
			</div>

	{% endblock %}

templates/base.html
<!DOCTYPE html>
<html>
<head>
	<title>{{ title }}</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
	<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
{% block extrahead %}
{% endblock %}
</head>
<body>

	<div class="row">
		<div class="col-md-6 mx-auto text-center">
			<div>
				{% with messages = get_flashed_messages(with_categories=true) %}
				{% if messages %}
				{% for category, message in messages %}
				{% if category == 'message' %}
				<div class="alert alert-warning alert-dismissible" role="alert">
					{% else %}
					<div class="alert alert-{{ category }} alert-dismissible" role="alert">
						{% endif %}
						{{ message }}
						  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
						    <span aria-hidden="true">&times;</span>
						  </button>
					</div>
					{% endfor %}
					{% endif %}
					{% endwith %}
				</div>
			</div>
		</div>
	</div>

{% block body %}

{% endblock %}

{% block extra_js %}
{% endblock %}
</body>
</html>

templates/confirm_withdrawal.html
{% extends "dashboard.html" %}


{% block dashbody %}


<div class="col-md-9">

		
<!-- 	<div class="row">
		
		{% if submit_button == 'resent-otp' %}
		<div class="col-md-3"><div class="col-md-3"><button class="btn btn-danger" href="{{ url_for('dashboard.confirm_withdrawals')}}">Cancel</button></div></div>
		<div class="col-md-6">
			<input type="text" class="form-control" placeholder="Enter OTP Code">

		</div>
		<div class="col-md-3"><button class="btn btn-primary btn-block" type="submit" name="submit_button" id="submit_button" value="confim-withdrawal">Confirm Withdrawals</button></div>
		{% else %}
		<button class="btn btn-primary ml-auto" type="submit" name="submit_button" id="submit_button" value="resend-otp">Initiate Bulk Withdrawal</button>
		{% endif %}
		
	</div>
	<br> -->
	<div class="row">
		<div class="container">
			
	<table class="table">
		<thead>

			<th scope="col">#</th>
			<th scope="col">User Email</th>
			<th scope="col">Amount</th>
			<th scope="col">Action</th>
			
		</thead>
		<tbody>

		{% for tlog in trlogs %}
			<tr scope="row">
				<td>{{ loop.index }}</td>
				<td>{{ tlog.get_user().email }}</td>
				<td>{{  tlog.get_amount() }}</td>
				<td>
	
				<form action="{{url_for('dashboard.confirm_withdrawals')}}" method="post" style="width:98%;">
				<input type="hidden" name="trlog" value="{{tlog.id}}">

				<div class="form-row"  style="margin-top:5%;">
					<button class="btn btn-success col-md-5 mr-auto" name="submit_button" value='confim-withdrawal'>Accept</button>

					<button class="btn btn-danger col-md-5  ml-auto" name="submit_button" value='deny-withdrawal'>Deny</button>
				</div>



			</form></td>
			</tr>
		{% endfor %}
	
		</tbody>
	</table>

		</div>

	</div>



 


</div>


{% endblock %}


{% block extra_js %}
<script>

$('.withdrawal-list-master').on('click', function(){
	$('.withdrawal-list-child').not(this).prop('checked', this.checked);
});

</script>
{% endblock %}

templates/dash_balance.html
				<div style="border:1px solid black; padding:5%;">
				<p class="text-left">Balance</p>
				<br>
				<p class="text-right">&#8358 {{ current_user.balance }}</p>
			</div>		

templates/dashboard.html
{% extends "base.html" %}

{% block body %}
	<div class="container" style="margin-top:15%;">
		<div class="row">
		{% include "sidenav.html" %}

		{% block dashbody %}
			<div class="col-md-3">

			{% include "dash_balance.html" %}		<br>	<p><a href="{{ url_for('dashboard.deposit')}}">Make A deposit</a></p>
				<p><a href="{{ url_for('dashboard.withdrawal')}}">Make a Withdrawal</a></p></div>
			<div class="col-md-6">
				<ul class="list-group">
{% for tlog in trlogs.items %}
  <li class="list-group-item">{{ tlog|safe }}</li>
</ul>
{% endfor %}
			</div>
			{% endblock %}
		</div>
	</div>


{% endblock %}

templates/deposit.html
{% extends "dashboard.html" %}

{% block dashbody %}

		<div class="col-md-3">
			{% include "dash_balance.html" %}
		<br>	
		
		<p><a href="{{ url_for('dashboard.withdrawal')}}">Make a Withdrawal</a></p>
	</div>
	<div class="col-md-6">
		<div class="row">
			<div class="container">

				<form action="{{ url_for('dashboard.deposit') }}" id="deposit-form" method="post">
					<label for="amount">Enter Amount</label>
					<div class="input-group mb-3">
					  <div class="input-group-prepend">
					    <span class="input-group-text" id="basic-addon1"> &#8358; </span>
					  </div>
						<input type="number" id="amount" name="amount" class="form-control col-md-6" placeholder="100 Minimum" aria-label="amount" aria-describedby="basic-addon1" required>
					</div>



					<br><button class="btn btn-success" 
					type="submit">Deposit</button></form>
				</div>
			</div>
	</div>



<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
	<div class="modal-dialog modal-dialog-centered" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title">Complete Deposit</h5>
				<button class="close" type="button" data-dismiss="modal" aria-label="Close"></button>
			</div>
			<div class="modal-body">
				<p><div id="paystackEmbedContainer"></div></p>
			</div>
		</div>
	</div>
</div>





















{% endblock %}

{% block extra_js %}
<script src="https://unpkg.com/axios/dist/axios.min.js"></script>
<script src="https://js.paystack.co/v1/inline.js"></script>




<script>
	var refcode = '';
	document.getElementById('deposit-form').addEventListener('submit', function(event){
		event.preventDefault();
		var amount = parseInt(document.getElementById('amount').value, 10);
		console.log('amount is ', amount)
		console.log('typeof amount is ', typeof(amount))
		console.log('amount >= 100 is ', amount >= 100)
		console.log('typeof(amount) == number is ', typeof(amount) == 'number')
		if ((typeof(amount) == 'number') && (amount >= 100)){
			axios.post('/deposit',
					{'amount': amount}
					).then(function(response){
						console.log('response is', response);
					
					//if (data.status == 201){
						$('#exampleModal').modal('show');
						// document.getElementById('exampleModal').modal('show')
						return payWithPaystack(response.data);
					})
					.catch(function (error){
						console.log('error is', error);
					});

		} else {

			alert('minimum Deposit is 100');
			return false;

		}



		});

function payWithPaystack(data){

	refcode = data.reference;
	console.log(data.reference);
	var handler = PaystackPop.setup({
		key: "{{ config.PAYSTACK_PUBLIC_KEY }}",
		email: data.email,
		amount: data.amount,
		ref: data.reference,
		container: 'paystackEmbedContainer',
		callback: function(resp){
          alert('success. transaction ref is ' + resp.reference);
      },
      onClose: function(){
          alert('window closed');
      }
	});	
	handler.openIframe();


}


$('body').bind('change', function(){
	console.log('document changed');
	$('iframe').bind('load', function(){
		console.log('iframe loaded')
		if ($("#paystack-ok:contains('Successful')").length > 0){
			console.log('deposit res is', refcode);
			axios.get('/deposit?ref=' + refcode)
			.then(function(response){
				console.log('response is', response);
				window.location(srvres.data.url)	
			})
			.catch(function(response){
				console.log('response is', response);
				alert('Oops! an error occured!');
			})

			}
	});
	
	});

async function verifyPayment(){
		url = "{{ url_for('dashboard.deposit')}}?ref=" + refcode	
		axios.get(url				
				).then(function(response){
					console.log(response)
				}).catch(function(response){
					console.log(response)
				})
			
		return true
}

$('body').bind('change', function(){
		$('#exampleModal').bind('hide.bs.modal', function(event){

			console.log(event);
			verifyPayment();
			if (confirm('Are you sure you want to confirm your transaction?')) {
				url = "{{ url_for('dashboard.deposit')}}?ref=" + refcode
			    window.location.href = "{{ url_for('dashboard.deposit')}}?ref=" + refcode
				
				} else {

					
			    // Do nothing!
			}
			
			return false;

		});
});


</script>

{% endblock %}

templates/login.html
{% extends "base.html" %}

{% block body %}
	<div class="container">

		<div class="row">
			<form action="{{url_for('auth.login')}}" method="post" class="col-md-8 mx-auto" style="margin-top:15%;">
				<h3 class="text-center">Login</h3>
				<div class="form-row">
					<label for="email">
						Email Address
					</label>
					<input type="text" class="form-control" name="email" id="email">
				</div>
				<div class="form-row">
					<label for="email">
						Password
					</label>
					<input type="password" class="form-control" name="password" id="password">
				</div>
				 {{ form.csrf_token }}
				<div class="form-row"  style="margin-top:5%;">
					<button class="btn btn-primary col-md-6 mx-auto">Submit</button>
				</div>
				<div class="row" style="margin-top:5%;">
					<div class="col-md-6"><a href="{{ url_for('auth.register')}}">Signup/Register</a></div>
					<div class="col-md-6 text-right"><a href="#">Forgot Password?</a></div>
				</div>
				
			</form>
		</div>
	</div>


{% endblock %}

templates/otp_setting.html
{% extends "dashboard.html" %}


{% block dashbody %}
<div class="col-md-4">	
	<div class="container">
		<div class="row">
			<form action="{{url_for('dashboard.otp_setting')}}" method="post" style="width:98%; margin-top:3%;">
				<div class="row">
					<div class="col-md-6">
						{% if otpstatus  %}
						<span class="badge badge-danger">OTP Enabled</span>

						{% else %}
						<span class="badge badge-success">OTP Disabled</span>
						{% endif %}

					</div>
					<div class="col-md-6">
						{% if otpstatus  %}


		<button class="btn btn-primary ml-auto btn-block" name="submit_button" placeholder="Enter OTP Here"
						 value='disable-otp'>Disable OTP</button>

						{% else %}

				<button class="btn btn-danger ml-auto btn-block" name="submit_button" placeholder="Enter OTP Here"
						 value='enable-otp'>Enable OTP</button>


						{% endif %}
					</div>


				</div>
			</form>
			<hr width="80%" align="right" style="margin-top:14%; margin-bottom:9%;"class="mr-auto">
			<form action="{{url_for('dashboard.otp_setting')}}" method="post" style="width:98%;">
				<div class="row">
					<label for="otp" class="text-right">								OTP
					</label>
					<input type="text" class="form-control" name='otp-code'  required>
				</div>


				<div class="form-row"  style="margin-top:5%;">



					<button class="btn btn-primary col-md-4 ml-auto" name="submit_button" placeholder="Enter OTP Here" value='submit-otp'>Submit OTP</button>
				</div>

			</form>

		</div>



	</div>
</div>

<div class="col-md-5">
	<ul class="list-group">
		{% for item in otplogs.items %}
		<li class="list-group-item">{{ item.message }}</li>
		{% endfor %}
	</ul>
</div>

{% endblock %}

templates/settings.html
{% extends "dashboard.html" %}
	{% block dashbody %}
		<div class="col-md-6">	
				<div class="container">

					<div class="row">
					<form action="{{url_for('dashboard.account_settings')}}" method="post" style="width:80%;">

						<div class="row">
							<label for="password">
								Current Password
							</label>
							<input type="text" class="form-control" name="current_password" id="current_password" placeholder="**********">
						</div>

						<br>

						<hr>

						<div class="row">
							<label for="password">
								New Password
							</label>
							<input type="text" class="form-control" name="password" id="password" placeholder="**********">
						</div>

						<div class="row">
							<label for="password_again">
								New Password Again
							</label>
							<input type="text" class="form-control" name="password_again" id="password_again" placeholder="**********">
						</div>

						<div class="form-row"  style="margin-top:5%;">
							<button class="btn btn-primary col-md-6 ml-auto">Change Password</button>
						</div>

					</form>

				</div>



				</div>
		</div>




{% endblock %}

templates/sidenav.html
<div class="col-md-3">
	<div class="list-group">
		<a href="{{ url_for('dashboard.dashboard') }}" class="list-group-item active">Dashboard</a>
		<a href="{{ url_for('dashboard.account_settings') }}" class="list-group-item">Settings</a>
		<a href="{{ url_for('dashboard.bank_settings')}}" class="list-group-item">Bank Account</a>
		<a href="{{ url_for('auth.logout') }}" class="list-group-item">Logout</a>
	</div>
</div>

templates/withdrawal.html
{% extends "dashboard.html" %}

{% block dashbody %}
			<div class="col-md-3">
				{% include "dash_balance.html" %}
	<br><p><a href="{{ url_for('dashboard.deposit')}}">Make A deposit</a></p><ul class="list-group">

  <li class="list-group-item">Cras justo odio</li>
  <li class="list-group-item">Dapibus ac facilisis in</li>
  <li class="list-group-item">Morbi leo risus</li>
  <li class="list-group-item">Porta ac consectetur ac</li>
  <li class="list-group-item">Vestibulum at eros</li>
</ul>
</div>
			<div class="col-md-6">
							<div class="row">
				<div class="container">

					<form action="{{ url_for('dashboard.withdrawal') }}" id="withdrawal-form" method="post">
						<label for="amount">Enter Amount</label>
					
				
									<div class="input-group mb-3">
					  <div class="input-group-prepend">
					    <span class="input-group-text" id="basic-addon1"> &#8358; </span>
					  </div>
							<input type="number" id="amount" name="amount" class="form-control col-md-6" placeholder="1000 Minimum" aria-label="amount" aria-describedby="basic-addon1">
					</div>



						<br><button class="btn btn-success" 
						type="submit">Withdraw</button></form>
					</div>
				</div>
			</div>


{% endblock %}



{% block extra_js %}



<script>
	$('#withdrawal-form').submit(function(e){
		
		// console.log(e);
		amount = parseInt($('#amount').val());
		if (amount < 1000){
			alert('minimum Withdrawal is 1000');
			return false;
		}
		if (amount > {{ current_user.balance }}){
			alert('Sorry, you can only withdraw up to your balance');
			return false;
		}

	});

</script>

{% endblock %}